// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#define GGML_CUDA_NO_MMA
#include "../mmq.cuh"

#if !defined(GGML_USE_HIP) && !defined(GGML_USE_MUSA)
DECL_MMQ_CASE(GGML_TYPE_Q8_0);
#endif
